In [ ]:
import pandas as pd

# EXTRACT: membaca data dari sumber (file CSV)
df_source = pd.read_csv('content/train.csv')

# Ambil subset kolom yang relevan untuk kebutuhan analisis tertentu
kolom_dibutuhkan = ['Survived', 'Pclass', 'Sex', 'Age', 'Fare', 'Embarked']

df_extracted = df_source[kolom_dibutuhkan].copy()
print('Data berhasil di-extract. Jumlah baris:', len(df_extracted))
df_extracted.head()

Data berhasil di-extract. Jumlah baris: 891

   Survived  Pclass     Sex   Age     Fare Embarked
0         0       3    male  22.0   7.2500        S
1         1       1  female  38.0  71.2833        C
2         1       3  female  26.0   7.9250        S
3         1       1  female  35.0  53.1000        S
4         0       3    male  35.0   8.0500        S

In [ ]:
data_etl = df_source[["Name", "Sex", "Age", "Survived"]]

data_etl.head()

                                                Name     Sex   Age  Survived
0                            Braund, Mr. Owen Harris    male  22.0         0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0         1
2                             Heikkinen, Miss. Laina  female  26.0         1
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0         1
4                           Allen, Mr. William Henry    male  35.0         0

In [ ]:
# TRANSFORM: membersihkan missing value
df_transformed = df_extracted.copy()
df_transformed['Age'] = df_transformed['Age'].fillna(df_transformed['Age'].median())
df_transformed['Embarked'] = df_transformed['Embarked'].fillna(df_transformed['Embarked'].mode()[0])

# TRANSFORM: membuat kolom baru (derived column) - kategori usia
def kategori_usia(usia):
  if usia < 18:
    return 'Anak-anak'
  elif usia < 60:
    return 'Dewasa'
  else:
   return 'Lansia'
df_transformed['kategori_usia'] = df_transformed['Age'].apply(kategori_usia)

# TRANSFORM: standardisasi nama kolom menjadi huruf kapital pada label
df_transformed['Sex'] = df_transformed['Sex'].str.capitalize()
print('Data berhasil ditransformasi.')
df_transformed.head()

Data berhasil ditransformasi.

   Survived  Pclass     Sex   Age     Fare Embarked kategori_usia
0         0       3    Male  22.0   7.2500        S        Dewasa
1         1       1  Female  38.0  71.2833        C        Dewasa
2         1       3  Female  26.0   7.9250        S        Dewasa
3         1       1  Female  35.0  53.1000        S        Dewasa
4         0       3    Male  35.0   8.0500        S        Dewasa

In [ ]:
import pandas as pd

# Mengambil data yang diperlukan dari dataset
data_etl = df_source[["Name", "Sex", "Age", "Survived"]].copy()

# Encode gender
data_etl["Sex"] = data_etl["Sex"].map({
    "male": 1,
    "female": 0
})

# Menambahkan kategori usia
data_etl["Kategori_Usia"] = pd.cut(
    data_etl["Age"],
    bins=[0, 18, 40, 60, 80],
    labels=["Anak", "Dewasa Muda", "Dewasa", "Lansia"]
)

# Menampilkan hasil transformasi
data_etl.head()

,Name,Sex,Age,Survived,Kategori_Usia
0,"Braund, Mr. Owen Harris",1,22.0,0,Dewasa Muda
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,Dewasa Muda
2,"Heikkinen, Miss. Laina",0,26.0,1,Dewasa Muda
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,Dewasa Muda
4,"Allen, Mr. William Henry",1,35.0,0,Dewasa Muda

In [ ]:
# LOAD: menyimpan data hasil transformasi ke file CSV baru
df_transformed.to_csv('/content/titanic_hasil_etl.csv', index=False)

print('Data berhasil disimpan ke titanic_hasil_etl.csv')
print('Jumlah baris:', len(df_transformed))
print('Jumlah kolom:', len(df_transformed.columns))
print('Kolom:', list(df_transformed.columns))

Data berhasil disimpan ke titanic_hasil_etl.csv
Jumlah baris: 891
Jumlah kolom: 7
Kolom: ['Survived', 'Pclass', 'Sex', 'Age', 'Fare', 'Embarked', 'kategori_usia']

In [ ]:
# LOAD: menyimpan data hasil transformasi ke file CSV baru
data_etl.to_csv("/content/titanic_clean.csv", index=False)

print("Dataset sudah disimpan sebagai titanic_clean.csv")
print("Jumlah baris:", len(data_etl))
print("Jumlah kolom:", len(data_etl.columns))
print("Kolom:", list(data_etl.columns))

Dataset sudah disimpan sebagai titanic_clean.csv
Jumlah baris: 891
Jumlah kolom: 5
Kolom: ['Name', 'Sex', 'Age', 'Survived', 'Kategori_Usia']

PRAKTIKUM 2

In [ ]:
kolom_dibutuhkan = ['Survived', 'Pclass', 'Sex', 'Age', 'Fare', 'Embarked']

df_extracted = df_source[kolom_dibutuhkan].copy()

print('Jumlah baris:', len(df_extracted))
print('Jumlah missing value setiap kolom:', df_extracted.isnull().sum())

df_extracted.head()

Jumlah baris: 891

Jumlah missing value setiap kolom: Survived      0
Pclass        0
Sex           0
Age         177
Fare          0
Embarked      2
dtype: int64

   Survived  Pclass     Sex   Age     Fare Embarked
0         0       3    male  22.0   7.2500        S
1         1       1  female  38.0  71.2833        C
2         1       3  female  26.0   7.9250        S
3         1       1  female  35.0  53.1000        S
4         0       3    male  35.0   8.0500        S

In [ ]:
df_transformed = df_extracted.copy()
df_transformed['Age'] = df_transformed['Age'].fillna(df_transformed['Age'].median())
df_transformed['Embarked'] = df_transformed['Embarked'].fillna(df_transformed['Embarked'].mode()[0])

def kategori_usia(u):
    if u < 18: return 'Anak-anak'
    elif u < 60: return 'Dewasa'
    else: return 'Lansia'

df_transformed['Kategori_Usia'] = df_transformed['Age'].apply(kategori_usia)
df_transformed['Sex'] = df_transformed['Sex'].str.capitalize()

print('\nJumlah missing value setiap kolom:')
print(df_transformed.isnull().sum())

df_transformed.head()

Jumlah missing value setiap kolom:
Survived         0
Pclass           0
Sex              0
Age              0
Fare             0
Embarked         0
Kategori_Usia    0
dtype: int64

   Survived  Pclass     Sex   Age     Fare Embarked Kategori_Usia
0         0       3    Male  22.0   7.2500        S        Dewasa
1         1       1  Female  38.0  71.2833        C        Dewasa
2         1       3  Female  26.0   7.9250        S        Dewasa
3         1       1  Female  35.0  53.1000        S        Dewasa
4         0       3    Male  35.0   8.0500        S        Dewasa

In [ ]:
df_transformed.to_csv('content/titanic_hasil_etl_praktikum_2.csv', index=False)

print('Jumlah baris:', len(df_transformed))
print('Jumlah kolom:', len(df_transformed.columns))
print('Kolom:', list(df_transformed.columns))

Jumlah baris: 891
Jumlah kolom: 7
Kolom: ['Survived', 'Pclass', 'Sex', 'Age', 'Fare', 'Embarked', 'Kategori_Usia']